[package]
edition = "2018"
name = "pinwheel_counter"
publish = false
version = "0.0.0"

[[bin]]
name = "counter"
path = "main.rs"

[dependencies]
pinwheel = { path = "../../" }
wasm-bindgen = "=0.2.73"

[dependencies.web-sys]
version = "0.3"
features = [
  "Document",
  "Window",
]
